<?php 
session_start();
header("Content-type:text/html;charset=utf-8");
define('DB_HOST','localhost');
define('DB_USER','root');
define('DB_PASSWORD','123456');
define('DB_DATABASE','moral');
define('DB_PORT',3308);
define('DB_PATH',dirname(dirname(__FILE__)));
?>