<?php
if(empty($_POST['name'])||empty($_POST['pw'])){
    skip('login.php','error','管理员用户名、密码不得为空！');
}
if(mb_strlen($_POST['name'],'utf-8')>32||mb_strlen($_POST['pw'],'utf-8')>32){
    skip('login.php','error','管理员用户名或密码过长！');
}
if(strtolower($_POST['vcode'])!=strtolower($_SESSION['vcode'])){
    skip('login.php','error','验证码输入错误！');
}
?>